# Returns values generated by custom implementations of both uniform
# and beta distributions.
df.custom.all <- function(n, k1, k2) {
  data.frame(xemp=f.dist(n=n, k1=k1, k2=k2),
             y='Рівномірний - генератор Ковею')
}

# Returns above + system uniform distribution.
df.custom.beta <- function(n, k1, k2) {
  rbind(df.custom.all(n, k1, k2),
        data.frame(xemp=f.dist(n=n, k1=k1, k2=k2, unif.custom=F),
                   y='Рівномірний - системний генератор'))
}

# Returns above + both system beta and F distributions.
df.all <- function(n, k1, k2) {
  rbind(df.custom.beta(n, k1, k2),
        data.frame(xemp=f.dist(n=n, k1=k1, k2=k2, unif.custom=F,
                               beta.custom=F),
                   y='Бета - системний генератор'),
        data.frame(xemp=rf(n=n, df1=k1, df2=k2),
                   y='Фішера - системний генератор'))
}

# Plots empirical distributions of results of different methods, combined in
# dataframe, generated by fun.df argument (with an appropriate signature).
f.pdf.plot <- function(fun.df=df.all, n=1000, k1, k2, xmax=5, precision=.1) {
  f.df <- fun.df(n, k1, k2)
  ggplot(f.df, aes(x = xemp, ..density..,  colour = y)) +
    geom_freqpoly(alpha = .1, binwidth = precision, position = "identity",
              stat = "bin") +
    coord_cartesian(xlim = c(0, xmax)) +
    ylab('Щільність') + xlab('Значення випадкової величини')
}

# The same as above, but instead plotting cdfs of results.
f.cdf.plot <- function(fun.df=df.all, n=1000, k1, k2, xmax=5, precision=.1) {
  f.df <- fun.df(n, k1, k2)
  ggplot(f.df, aes(x = xemp, colour = y)) +
    stat_ecdf(pad = F) + coord_cartesian(xlim = c(0, xmax)) +
    ylab('Кумулятивна щільність') + xlab('Значення випадкової величини')
}